# Generated by Django 3.2.23 on 2023-12-10 10:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_shopping_cart',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
